### ISSUE TITLE
Questions about the model FLOP, GPU memory cost, and speed

### ISSUE THREAD

**Issue by pzSuen** [Zhengyushan/kat#1]
Hello,
very impressed with your work.

But I have a few small questions about Table1 and Table2, specifically about the model FLOP, GPU memory cost, and speed.

As far as I know, the size of each slide is different, which causes the efficiency of each image calculation to be different.

So my question is, what size slice are you computing on, and how many patches are there?

Looking forward to your reply.

Yours.
pzSuen.

**Comment by Zhengyushan** [comment]
Hi,

 

Very thanks for your attention to our work.

 

These results were calculated under a consistent size of patches for each dataset because we need to pad the data to a fixed tensor size for batch training. We assigned a max patch size of 2048 for the gastric dataset since we found most of the patch number in this dataset not exceed 2048. Similarly, we assigned the max patch size as 4096 for our endometrial dataset. So, the GPU memory, speed, and FLOPs for the gastric dataset are the results for 2048 patches and the results for the endometrial dataset are 4096 patches.

 

Please feel free to contact me if you have other questions. 

 

我看你头像是567，是在哈尔滨高校的同僚吗？方便的话我们也可以用中文交流。

 

Sincerely,

Yushan Zheng

郑钰山

 

发件人: ***@***.*** ***@***.***> 代表 pzSuen
发送时间: 2022年11月13日 13:13
收件人: Zhengyushan/kat ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Zhengyushan/kat] Questions about the model FLOP, GPU memory cost, and speed (Issue #1)

 

Hello,
very impressed with your work.

But I have a few small questions about Table1 and Table2, specifically about the model FLOP, GPU memory cost, and speed.

As far as I know, the size of each slide is different, which causes the efficiency of each image calculation to be different.

So my question is, what size slice are you computing on, and how many patches are there?

Looking forward to your reply.

Yours.
pzSuen.

**Comment by pzSuen** [comment]
谢谢您的快速回复。

是的，我是哈工大计算学部的一名在读博士生，目前研究方向是病理图像分析。
我在各大顶会、顶刊上都看到过您的工作，真是久仰大名！

您的回答解决了我的疑问。

那接下来我有下面几个小问题：
1. 请问您的2048/4096的Patch是从20倍放大的切片上裁剪的吗？是否进行背景区域的过滤？以及如果保证切片标签赋值给Patch保证标签不变化？
2. 您是否在全切片上测试您的模型？比如图像尺寸在100000×100000数量级。
3. 您的结果中只展示了KAT在各种参数下的计算量和显存，那您是否对比与TransMIL等方法的计算量和显存？

期待您的再次回复！
